outputs:
  - filename: "input_conversations/train.jsonl"
    global_limit: 100000
    sources:
      - name: "sharegpt"
        splits:
          all: 0
      - name: "ultrachat"
        splits:
          train_gen: 10000
          train_sft: 10000
      - name: "mtbench"
        splits:
          all: 0
      - name: "daring-anteater"
        splits:
          all: 0
      - name: "magpie"
        splits:
          300k: 0
          500k: 0
          1M: 0
      - name: "nemotron-post-training-v2"
        splits:
          chat: 20000
          stem: 20000
          math: 20000
          code: 20000
          multilingual_ja: 10000
          multilingual_it: 10000
          multilingual_de: 10000
          multilingual_es: 10000
          multilingual_fr: 10000
